### ISSUE TITLE
bug: rects having weird corners when having an outlineComp

### ISSUE THREAD

**Issue by amyspark-ng** [marklovers/kaplay#11]
I have a rect object which im adding an outline to, it looks like this
![image](https://github.com/marklovers/kaplay/assets/92493175/53768296-427a-49ff-bf6b-cb0c5b727dbf)

The code is:
`kaboom()

let square = add([
	rect(100, 100, { radius: 10 }),
	pos(center()),
	outline(10, BLACK)
])`

**Comment by lajbel** [comment]
@mflerackers

**Comment by mflerackers** [comment]
The reason is quite simple. Line joins are not supported. So even if you calculate the points for the line correctly, they aren't nicely joined. Lines are just drawn as separate segments with a butt linecap. So where lines at an angle join, you are going to have gaps.
The solution is to add line join support for at least bevel join. Then the problem of the round rectangle outline is automatically fixed as well.

**Comment by amyspark-ng** [comment]
was fixed in: https://github.com/marklovers/kaplay/commit/40e5d8cfdd7f7831b439aca2b4088f9401afe137
