### ISSUE TITLE
Moving to PIXIjs as backend

### ISSUE THREAD

**Issue by rishavs** [marklovers/kaplay#156]
Hi

With the current change pf Kaboom to Kaplay, I was wondering if the new maintainers are interested in moving the Kaplay backend over to pixijs.
Pixijs is one of the most performant web rendering frameworks out there and by using it as a backend, you will be building upon a battle tested framework.

I think Kaboom/Kaplay's biggest strength are its api, and by moving to a abstracted external backend, you will be able to focus more on the userland stuff like api design, documentation, extensions etc.

**Comment by mflerackers** [comment]
Most likely not. Kaboom isn't slow due to its rendering, but due to the lack of optimization anywhere else but the rendering. So focusing on replacing the backed would solve exactly nothing. You'd just wind up with another back-end you no longer have control over, and everything would be as slow as it was before.

**Comment by rishavs** [comment]
Thanks for replying. One more question - given that now Kaboom is archived, is it possible to publish a roadmap for Kaplay to understand its near future?

**Comment by mflerackers** [comment]
Currently we are stabilizing features and reworking the build, docs and examples for a clean and stable 3001 release. After that we will start planning 400x. A list of new finished features for 3001 can be found in the changelog. Some others like particle systems and navigation meshes are currently in testing. They might make it in time, or not.
400x will most likely have keyframe animation instead of just tweens between two values. With linear or various splines animation and path following (first derivative of motion). Textured shapes and outlines, for non-tiled platformers for example. A Shape primitive supporting curved shapes for non-polygonal drawing. Better spatial structures like quadtree and sweep&prune to speed up spatial queries. A working circle area (has been disabled since Kaboom switched to SAT). Isometric tile support (if I don't find time to add it in 3001). And other things I can't remember right now.

**Comment by rishavs** [comment]
Thanks

**Comment by SpcFORK** [comment]
Yeah, KAPLAY will have a ton of changes since it won't be under the control of Replit and stuff no more, lots more freedom to add whatever, regardless of being paid or not
